# Generated by Django 3.1.6 on 2021-02-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('historias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historias',
            name='equipo',
        ),
    ]
