# Generated by Django 3.1.6 on 2021-03-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tareas', '0001_initial'),
        ('impedimentos', '0001_initial'),
        ('historias', '0001_initial'),
        ('equipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la revision')),
                ('que_ha_hecho', models.CharField(blank=True, max_length=500, null=True, verbose_name='Qué ha hecho')),
                ('que_ha_hara', models.CharField(blank=True, max_length=500, null=True, verbose_name='Qué ha hará')),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True, verbose_name='Comentarios')),
                ('equipo_rev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipo.equipo')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='historias.historias')),
                ('impedimentos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='impedimentos.impedimentos')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tareas.tareas')),
            ],
        ),
    ]
