# Generated by Django 3.1.6 on 2021-02-24 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('revision', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='que_ha_hara',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Qué ha hará'),
        ),
        migrations.AddField(
            model_name='revision',
            name='que_ha_hecho',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Qué ha hecho'),
        ),
    ]
