# Generated by Django 3.1.6 on 2021-02-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impedimentos', '0001_initial'),
        ('revision', '0002_auto_20210223_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='revision',
            name='impedimentos',
            field=models.ManyToManyField(to='impedimentos.Impedimentos'),
        ),
    ]
