# Generated by Django 3.1.6 on 2021-02-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('impedimentos', '0001_initial'),
        ('revision', '0003_revision_impedimentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revision',
            name='impedimentos',
            field=models.ManyToManyField(to='impedimentos.Impedimentos'),
        ),
    ]
